import Footer from '../content/footer'
import Header from '../content/header'

import { ContextProvider } from '../content/userContext'
import '../styles/global.css'
import Head from 'next/head'


// function MyApp({ Component, pageProps }) {

//   return (
//     <ContextProvider>
//       <Head>
//         <title>Bloggy</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="logoooo.png" />
//       </Head>

//         <Header/>
//         <Component {...pageProps} />
//         <Footer/>
//     </ContextProvider>
  
//   )
// }

// export default MyApp


import { createBrowserSupabaseClient } from '@supabase/auth-helpers-nextjs'
import { SessionContextProvider } from '@supabase/auth-helpers-react'
import {useState} from 'react'

function MyApp({ Component, pageProps }) {
  const [supabase] = useState(() => createBrowserSupabaseClient())

  return (
    <SessionContextProvider supabaseClient={supabase} initialSession={pageProps.initialSession}>
        <Head>
        <title>Bloggy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="logoooo.png" />
        </Head>
     <Component {...pageProps} />
     </SessionContextProvider>
  )
}
export default MyApp
