import Footer from '../content/footer'
import Header from '../content/header'
import { ContextProvider } from '../content/userContext'
import '../styles/global.css'
import Head from 'next/head'


function MyApp({ Component, pageProps }) {

  return (
    <ContextProvider>
      <Head>
        <title>Bloggy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="logoooo.png" />
      </Head>

        <Header/>
        <Component {...pageProps} />
        <Footer/>
    </ContextProvider>
  

  )
}

export default MyApp
