import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About US </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         About us 
        </h1>
        <br></br>

        <div className={styles.grid}>
         
           <div className={styles.card}>
            <h2>Messaoudi Fares &rarr;</h2>
            <p>Etudiante 4 eme année en majeur Systeme d'informations </p>
            <br></br>
            <p > A l'ECE Paris depuis 2019</p>
            </div>

           <div className={styles.card}>
            <h2>Lydia Zouitene &rarr;</h2>
            <p>Etudiante 4 eme année en majeur Systeme d'informations </p>
            <br></br>
            <p > A l'ECE Paris depuis 2021</p>
          </div>          
        </div>
      </main>

      <footer className={styles.footer}>

      <Link href="/about"> 
           <a> About
          </a>
          </Link>

          <Link href="/contacts"> 
          <a >
            Contacts
          </a>
          </Link>
          
          <Link href="/articles"> 
          <a >
          Articles
          </a>
          </Link>

          <Link href="/"> 
          <a >
          HomePage
          </a>
          </Link>
</footer>
    </div>
  )
}
