import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/s.module.css'
import Footer from '../content/footer.js'
import Header from '../content/header'




export default function amerique() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bloggy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="logoooo.png" />
      </Head>
      <Header/>
      
      <main className={styles.main} >
      <p className={styles.description}>
        <a  className={styles.card}>
         <strong>Choose which teams you want to know more about ! </strong> 
         </a>
        </p>  

      <div className={styles.grid}>
        <a href="/usa"
            className={styles.card}>
            <h2>USA &rarr;</h2>
            <img src="amerique.png" width="400" length="400" alt="amerique image"/>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Canada &rarr;</h2>
            <img src="afrique.png" width="400"  length="400"  alt="afrique image"/>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Mexique &rarr;</h2>
            <img src="asiii2.png" width="400" length="400" alt="asia image"/>
          </a>

         
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Costa Rica &rarr;</h2>
            <img src="europe12.png" width="400" length="400" alt="europe image"/>
          </a>
        </div>
        
      
      </main>
      
      <p className={styles.description}>
          Get to know more about us ! 
         
          <a href="/about" className={styles.card}>
          <code className={styles.code}>click here </code> </a>
          
        </p>
        
        <Footer/>
  
    </div>
  )
}