import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Articles() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Articles </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>

          <h1 className={styles.title}>
           Articles 
          </h1>
          <br></br>
        
        <div className={styles.grid}>
           
             <div className={styles.card}>
             <img
                src="https://www.123comparer.fr/photoProd/zoom/3343/apple-iphone-13-256go-product-red-302747111.png"
                alt="car"
                width="50" 
                height="50" 
            />
              <h2>Iphone 13  &rarr;</h2>
                <ul>
                <li>Stockage : 128 Gb</li>
                <li>Couleur : Rouge</li>
                <li>IMEI : 76543234567654</li>
                </ul>
              </div>

             <div className={styles.card}>
                 <img
                src="https://www.backmarket.fr/cdn-cgi/image/format=auto,quality=75,width=1920/https://d1eh9yux7w8iql.cloudfront.net/product_images/304345_2a60ab2e-8178-4303-b2a9-945f0d319e18.jpg"
                alt="car"
                width="50" 
                height="50" />
                <h2>Ipad Mini 3  &rarr;</h2>
                <ul>
                <li>Stockage : 256 Gb</li>
                <li>Couleur : Gris</li>
                <li>IMEI : 765433546765</li>
                </ul>
              </div>     
          </div>
        </main>
  
      <footer className={styles.footer}>

      <Link href="/about"> 
           <a> About
          </a>
          </Link>

          <Link href="/contacts"> 
          <a >
            Contacts
          </a>
          </Link>
          
          <Link href="/articles"> 
          <a >
          Articles
          </a>
          </Link>

          <Link href="/"> 
          <a >
          HomePage
          </a>
          </Link>
        
      </footer>
    </div>
  )
}
