import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Bienvenue sur la HomePage en <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <br></br>

        <div className={styles.grid}>
          <Link href="/about"> 
           <a className={styles.card}>
            <h2>About &rarr;</h2>
            <p>Sur cette page, retrouvez toute les informations nous concernant.</p>
          </a>
          </Link>

          <Link href="/contacts"> 
          <a className={styles.card}>
            <h2>Contacts &rarr;</h2>
            <p>Sur cette page, veuillez retrouvez tout nos contacts</p>
          </a>
          </Link>
          
          <Link href="/articles"> 
          <a className={styles.card}>
            <h2>Articles &rarr;</h2>
            <p>
              Cette page contiendra la liste effectives de tout nos articles.
            </p>
          </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
