import { useRouter } from 'next/router'
import { useContext, useEffect } from 'react'
import Head from 'next/head'
import UserContext from '../components/UserContext'
import { useSupabaseClient, useSession } from '@supabase/auth-helpers-react'
import { useState } from 'react'

export default function Contact2() {


  return (
    <>
      <Head>
        <title>WebTech - user signedin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      { 
        <>
          <button
            className="rounded px-3 py-2 text-white bg-slate-500 hover:bg-blue-500"
          >
            Logout
          </button>
          

    <div className="form-widget">
      <div>
        <label htmlFor="email">Email</label>
        <input id="email" type="text" disabled />
      </div>
      <div>
        <label htmlFor="username">Username</label>
        <input
          id="username"
          type="text"
        />
      </div>

      <div>
        <button
          className="button primary block"
        >
          {'Update'}
        </button>
      </div>
    </div>
        </>
      }
    </>
  )
}
